# SPDX-FileCopyrightText: 2022 - 2024 Orthanc Team SRL <info@orthanc.team>
#
# SPDX-License-Identifier: CC0-1.0

# This compose file is an addition to the main docker-compose.yml file.
# It extends the first setup with MedDream publications


version: "3"
services:

  nginx:
    depends_on: [orthanc, orthanc-auth-service, meddream-viewer]
    environment:
      ENABLE_MEDDREAM: "true"

  orthanc:
    environment:
#      ORTHANC__ORTHANC_EXPLORER_2__SHARES__ENABLE_MED_DREAM_INSTANT_LINKS: "true"
#      ORTHANC__ORTHANC_EXPLORER_2__SHARES__TYPE: "meddream-viewer-publication"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_OPEN_IN_MED_DREAM_VIEWER: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__MED_DREAM_VIEWER_PUBLIC_ROOT: "http://localhost/meddream/"
      ORTHANC__ORTHANC_EXPLORER_2__TOKENS__SHARE_TYPE: "meddream-viewer-publication"

  orthanc-auth-service:
    environment:
      MEDDREAM_TOKEN_SERVICE_URL: "http://meddream-token-service:8088/v3/generate"
      PUBLIC_MEDDREAM_ROOT: "http://localhost/meddream/"

  # An orthanc dedicated for the MedDream viewer.  It has no access control since it
  # is accessible only from inside the Docker network
  orthanc-for-meddream:
    image: orthancteam/orthanc:24.12.0
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
      - ./demo-setup/meddream/meddream-plugin.py:/scripts/meddream-plugin.py
    depends_on: [orthanc-db]
    restart: unless-stopped
    env_file:
      - ./demo-setup/common-orthanc.env
    environment:
      ORTHANC__NAME: "Orthanc for MedDream"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC__PYTHON_SCRIPT: "/scripts/meddream-plugin.py"
      ORTHANC__AUTHENTICATION_ENABLED: "false"

  meddream-token-service:
    image: orthancteam/meddream-token-service
    restart: unless-stopped
    # remove in prod !
    ports: ["8088:8088"]

  meddream-viewer:
    image: orthancteam/meddream-viewer
    restart: unless-stopped
    depends_on:
      - orthanc-for-meddream
    environment:
      integration: "study"
      TOKEN_SERVICE_ADDRESS: "http://meddream-token-service:8088/v3/validate"
      ORTHANC_BASE_URL: "http://orthanc-for-meddream:8042"
      ORTHANC_USER: "orthanc-meddream-user"
      ORTHANC_MEDDREAM_PYTHON_PLUGIN_ENABLED: "true"
      MEDDREAM_ADMIN_PASSWORD: "admin"
    volumes:
      - meddream-license:/opt/meddream/license

volumes:
  meddream-license:
