version: "3"
services:

  nginx:
    image: orthancteam/orthanc-nginx:25.2.1
    depends_on:
      - orthanc
      - orthanc-auth-service
      - orthanc-for-shares
    restart: unless-stopped
    ports:
      - "8080:80"
# if setting ENABLE_HTTPS: "true" env var, uncomment the following 4 lines and comment the line with 'ports: ["80:80"]'
#    ports: ["443:443"]
#    volumes:
#      - /.../crt.pem:/etc/nginx/tls/crt.pem
#      - /.../key.pem:/etc/nginx/tls/key.pem
    environment:
      ENABLE_ORTHANC: "true"
      ENABLE_ORTHANC_FOR_SHARES: "true"
      ENABLE_ORTHANC_TOKEN_SERVICE: "false"
      ENABLE_HTTPS: "false"
      ENABLE_OHIF: "true"

  orthanc:
    image: orthancteam/orthanc:25.4.2
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
    depends_on:
      - orthanc-db
    restart: unless-stopped
    environment:
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__POSTGRESQL__HOST: "orthanc-db"
      ORTHANC__POSTGRESQL__TRANSACTION_MODE: "ReadCommitted"
      ORTHANC_JSON: |
        {
          "Name": "Orthanc",
          "OrthancExplorer2": {
            "IsDefaultUI": true,
            "UiOptions": {
              "EnableShares": true,
              "DefaultShareDuration": 0,
              "ShareDurations": [0, 7, 15, 30, 90, 365],
              "EnableOpenInOhifViewer3": true,
              "OhifViewer3PublicRoot": "${OHIF_VIEWER_PUBLIC_ROOT}"
            },
            "Tokens": {
              "ShareType": "stone-viewer-publication"
            }
          },
          "AuthenticationEnabled": true,
          "RegisteredUsers": {
            "${ORTHANC_ADMIN_USER}": "${ORTHANC_ADMIN_PASS}"
          },
          "Authorization": {  // the auth-plugin is used only to generate tokens when sharing a study
            //"WebServiceRootUrl": "http://orthanc-auth-service:8000/",
            "WebServiceTokenCreationBaseUrl": "http://orthanc-auth-service:8000/tokens/",
            "WebServiceUsername": "share-user",
            "WebServicePassword": "${ORTHANC_SERVICE_PASSWORD}"
            //"CheckedLevel": "studies"
          }
        }

  orthanc-for-shares:
    image: orthancteam/orthanc:25.4.2
    volumes:
      - orthanc-storage:/var/lib/orthanc/db
    depends_on:
      - orthanc-db
    restart: unless-stopped
    environment:
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__POSTGRESQL__HOST: "orthanc-db"
      ORTHANC__POSTGRESQL__TRANSACTION_MODE: "ReadCommitted"
      ORTHANC_JSON: |
        {
          "Name": "Orthanc",
          "OrthancExplorer2": {
            "IsDefaultUI": true,
            "UiOptions": {
              "EnableShares": true,
              "DefaultShareDuration": 0,
              "ShareDurations": [0, 7, 15, 30, 90, 365]
            },
            "Tokens": {
              "ShareType": "stone-viewer-publication"
            }
          },
          "AuthenticationEnabled": false,     // because it is handled by the authorization plugin
          "Authorization": {
            "WebServiceRootUrl": "http://orthanc-auth-service:8000/",
            "WebServiceUsername": "share-user",
            "WebServicePassword": "${ORTHANC_SERVICE_PASSWORD}",
            "StandardConfigurations": [
              "osimis-web-viewer",
              "stone-webviewer",
              "orthanc-explorer-2"     // required for the token-landing page
            ],
            "CheckedLevel": "studies"
          },
          "DicomWeb": {
            "Enable": true,
            "PublicRoot": "/orthanc/dicom-web/"
          }
        }

  orthanc-auth-service:
    image: orthancteam/orthanc-auth-service:25.2.1
    restart: unless-stopped
    environment:
      SECRET_KEY: "${ORTHANC_SERVICE_PASSWORD}"
      #PERMISSIONS_FILE_PATH: "path_to_the file"
      PUBLIC_ORTHANC_ROOT: "${PUBLIC_ORTHANC_ROOT}/shares/"
      PUBLIC_LANDING_ROOT: "${PUBLIC_LANDING_ROOT}"
      PUBLIC_OHIF_ROOT: "${OHIF_VIEWER_PUBLIC_ROOT}"
      USERS: |
        {
          "share-user": "${ORTHANC_SERVICE_PASSWORD}"
        }

  ohif:
    image: orthancteam/ohif-v3:25.2.1
    restart: unless-stopped
    # Uncomment to override OHIF config:
    # volumes:
    #   - ./ohif-app-config.js:/usr/share/nginx/html/app-config.js

  orthanc-db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - orthanc-db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes:
  orthanc-storage:
  orthanc-db:
