# SPDX-FileCopyrightText: 2022 - 2025 Orthanc Team SRL <info@orthanc.team>
#
# SPDX-License-Identifier: CC0-1.0

name: build-orthanc-share

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:

  build-orthanc-share:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1

      - name: Run python tests
        run: |
          pip install -r sources/requirements.txt
          ./sources/tests/run-tests.sh

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker (orthanc-nginx)
        id: meta-orthanc-nginx
        uses: docker/metadata-action@v5
        with:
          images: orthancteam/orthanc-nginx
          labels: |
            org.opencontainers.image.title=orthanc-nginx
            org.opencontainers.image.vendor=Orthanc Team SRL

      - name: Extract metadata (tags, labels) for Docker (orthanc-nginx-certbot)
        id: meta-orthanc-nginx-certbot
        uses: docker/metadata-action@v4
        with:
          images: orthancteam/orthanc-nginx-certbot
          labels: |
            org.opencontainers.image.title=orthanc-nginx-certbot
            org.opencontainers.image.vendor=Orthanc Team SRL

      - name: Extract metadata (tags, labels) for Docker (orthanc-auth-service)
        id: meta-orthanc-auth-service
        uses: docker/metadata-action@v5
        with:
          images: orthancteam/orthanc-auth-service
          labels: |
            org.opencontainers.image.title=orthanc-auth-service
            org.opencontainers.image.vendor=Orthanc Team SRL

      - name: Extract metadata (tags, labels) for Docker (meddream-viewer)
        id: meta-meddream-viewer
        uses: docker/metadata-action@v5
        with:
          images: orthancteam/meddream-viewer
          labels: |
            org.opencontainers.image.title=meddream-viewer
            org.opencontainers.image.vendor=Orthanc Team SRL

      - name: Extract metadata (tags, labels) for Docker (meddream-token-service)
        id: meta-meddream-token-service
        uses: docker/metadata-action@v5
        with:
          images: orthancteam/meddream-token-service
          labels: |
            org.opencontainers.image.title=meddream-token-service
            org.opencontainers.image.vendor=Orthanc Team SRL

      - name: Extract metadata (tags, labels) for Docker (orthanc-keycloak)
        id: meta-orthanc-keycloak
        uses: docker/metadata-action@v5
        with:
          images: orthancteam/orthanc-keycloak
          labels: |
            org.opencontainers.image.title=orthanc-keycloak
            org.opencontainers.image.vendor=Orthanc Team SRL

      - name: Extract metadata (tags, labels) for Docker (ohif-v3)
        id: meta-ohif-v3
        uses: docker/metadata-action@v5
        with:
          images: orthancteam/ohif-v3
          labels: |
            org.opencontainers.image.title=ohif-v3
            org.opencontainers.image.vendor=Orthanc Team SRL

      - name: Build and push orthanc-nginx Docker image
        uses: docker/build-push-action@v5
        with:
          context: sources/
          file: sources/nginx/Dockerfile.orthanc-nginx
          push: true
          tags: ${{ steps.meta-orthanc-nginx.outputs.tags }}
          labels: ${{ steps.meta-orthanc-nginx.outputs.labels }}

      - name: Build and push orthanc-nginx-certbot Docker image
        uses: docker/build-push-action@v4
        with:
          context: sources/
          file: sources/nginx/Dockerfile.orthanc-nginx-certbot
          push: true
          tags: ${{ steps.meta-orthanc-nginx-certbot.outputs.tags }}
          labels: ${{ steps.meta-orthanc-nginx-certbot.outputs.labels }}

      - name: Build and push orthanc-auth-service Docker image
        uses: docker/build-push-action@v5
        with:
          context: sources/
          file: sources/Dockerfile.orthanc-auth-service
          push: true
          tags: ${{ steps.meta-orthanc-auth-service.outputs.tags }}
          labels: ${{ steps.meta-orthanc-auth-service.outputs.labels }}

      - name: Build and push meddream-viewer Docker image
        uses: docker/build-push-action@v5
        with:
          context: sources/meddream/viewer
          file: sources/meddream/viewer/Dockerfile.meddream-viewer
          push: true
          tags: ${{ steps.meta-meddream-viewer.outputs.tags }}
          labels: ${{ steps.meta-meddream-viewer.outputs.labels }}

      - name: Build and push meddream-token-service Docker image
        uses: docker/build-push-action@v5
        with:
          context: sources/meddream/token-service
          file: sources/meddream/token-service/Dockerfile.meddream-token-service
          push: true
          tags: ${{ steps.meta-meddream-token-service.outputs.tags }}
          labels: ${{ steps.meta-meddream-token-service.outputs.labels }}

      - name: Build and push orthanc-keycloak Docker image
        uses: docker/build-push-action@v5
        with:
          context: sources/
          file: sources/keycloak/Dockerfile.orthanc-keycloak
          push: true
          tags: ${{ steps.meta-orthanc-keycloak.outputs.tags }}
          labels: ${{ steps.meta-orthanc-keycloak.outputs.labels }}

      - name: Build and push ohif-v3 Docker image
        uses: docker/build-push-action@v5
        with:
          context: sources/ohif/
          file: sources/ohif/Dockerfile.ohif-v3
          push: true
          tags: ${{ steps.meta-ohif-v3.outputs.tags }}
          labels: ${{ steps.meta-ohif-v3.outputs.labels }}

      - name: Docker Hub Description (orthanc-nginx)
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: orthancteam/orthanc-nginx
          short-description: Web service to run in front of Orthanc to handle sharing of studies & admin access
          readme-filepath: sources/README-dockerhub-orthanc-nginx.md

      - name: Docker Hub Description (orthanc-nginx-certbot)
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: orthancteam/orthanc-nginx-certbot
          short-description: Web service to run in front of Orthanc to handle sharing of studies & admin access (including certbot)
          readme-filepath: sources/README-dockerhub-orthanc-nginx-certbot.md

      - name: Docker Hub Description (orthanc-auth-service)
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: orthancteam/orthanc-auth-service
          short-description: Web service to run next to orthanc to handle authentication, authorization and sharing of studies
          readme-filepath: sources/README-dockerhub-orthanc-auth-service.md

      - name: Docker Hub Description (orthanc-keycloak)
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: orthancteam/orthanc-keycloak
          short-description: Web service to run in front of Orthanc to handle users/roles management
          readme-filepath: sources/README-dockerhub-orthanc-keycloak.md

      - name: Docker Hub Description (ohif-v3)
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: orthancteam/ohif-v3
          short-description: Web service to run next to Orthanc to host the OHIF viewer
          readme-filepath: sources/README-dockerhub-ohif-v3.md
